---
- name: List files in a directory on the target host
  hosts: localhost
  become: true # Set to true if you need sudo privileges
  tasks:
    - name: "Remove Old Folder"
      ansible.builtin.file:
        path: /var/www/project
        state: absent

    - name: Create a folder if it does not exist
      ansible.builtin.file:
        path: /var/www/project
        state: directory
        mode: "0755"

    - name: Copy File to /var/www/html
      command: cp -f project.tar.gz /var/www/project

    - name: Extract File
      command: tar --overwrite -xzvf /var/www/project/project.tar.gz

    - name: "Remove file"
      ansible.builtin.file:
        path: var/www/project/project.tar.gz
        state: absent
