name: PHP Composer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Compress project file
        run: tar -czvf ./project.tar.gz ./vendor ./composer.json ./composer.lock ./index.php

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github
          key: ${{ secrets.ID_RSA_PRIVATE }}
          known_hosts: ${{ secrets.HOST_IP }}

      - name: SSH Keyscan
        run: |
          ssh-keyscan -p 22 -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts

      - name: Create Pub Key
        run: |
          ls -lath ~/.ssh/
          ssh-copy-id -i ~/.ssh/github ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}
          ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}
